version: '3'
services:
  dev_node:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - dev_mysql
  dev_mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
