name: Node.js CI

on:
  push:
    branches:
      - develop
      - feature/deploy
env:
  PROJECT_NAME: potato-backend
  BUCKET_NAME: potato-codedeploy-bucket
  BUCKET_REGION: ap-northeast-2

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Npm Install, build and test
        run: |
          npm install
          npm run build
        env:
          CI: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Make deploy/month-app/build/libs/
        run: mkdir -p deploy/

      - name: Copy deploy script into deploy/
        run: cp appspec.yml docker-compose.*yml ./scripts/run.sh deploy/

      - name: Zip deploy/
        run: zip -r deploy.zip deploy

      - name: Upload to S3
        run: aws s3 cp deploy.zip s3://${BUCKET_NAME}/${PROJECT_NAME}-${GITHUB_SHA}.zip --region ${BUCKET_REGION}

      - name: Code Deploy
        env:
          CODE_DEPLOY_APP: potato-code-deploy
          CODE_DEPLOY_GROUP: dev
        run: aws deploy create-deployment --application-name ${CODE_DEPLOY_APP} --deployment-group-name ${CODE_DEPLOY_GROUP} --s3-location bucket=${BUCKET_NAME},bundleType=zip,key=${PROJECT_NAME}-${GITHUB_SHA}.zip
